@startuml AppLogic
state "AppLogic State" as ankitaiso_app_state_AppLogic_State {
  state "InGame" as ankitaiso_app_state_AppLogic_State_InGame
  state "LeavingGame" as ankitaiso_app_state_AppLogic_State_LeavingGame
  state "LeavingMenu" as ankitaiso_app_state_AppLogic_State_LeavingMenu
  state "LoadingSaveFile" as ankitaiso_app_state_AppLogic_State_LoadingSaveFile
  state "MainMenu" as ankitaiso_app_state_AppLogic_State_MainMenu
  state "SplashScreen" as ankitaiso_app_state_AppLogic_State_SplashScreen
}

ankitaiso_app_state_AppLogic_State_InGame --> ankitaiso_app_state_AppLogic_State_LeavingGame : EndGame
ankitaiso_app_state_AppLogic_State_LeavingGame --> ankitaiso_app_state_AppLogic_State_InGame : FadeOutFinished
ankitaiso_app_state_AppLogic_State_LeavingGame --> ankitaiso_app_state_AppLogic_State_MainMenu : FadeOutFinished
ankitaiso_app_state_AppLogic_State_LeavingMenu --> ankitaiso_app_state_AppLogic_State_InGame : FadeOutFinished
ankitaiso_app_state_AppLogic_State_LeavingMenu --> ankitaiso_app_state_AppLogic_State_LoadingSaveFile : FadeOutFinished
ankitaiso_app_state_AppLogic_State_LoadingSaveFile --> ankitaiso_app_state_AppLogic_State_InGame : SaveFileLoaded
ankitaiso_app_state_AppLogic_State_MainMenu --> ankitaiso_app_state_AppLogic_State_LeavingMenu : LoadGame
ankitaiso_app_state_AppLogic_State_MainMenu --> ankitaiso_app_state_AppLogic_State_LeavingMenu : NewGame
ankitaiso_app_state_AppLogic_State_SplashScreen --> ankitaiso_app_state_AppLogic_State_MainMenu : FadeOutFinished

ankitaiso_app_state_AppLogic_State_InGame : OnEnter → ShowGame
ankitaiso_app_state_AppLogic_State_InGame : OnExit → HideGame
ankitaiso_app_state_AppLogic_State_LeavingGame : OnFadeOutFinished → RemoveExistingGame, SetupGameScene
ankitaiso_app_state_AppLogic_State_LeavingMenu : OnEnter → FadeToBlack
ankitaiso_app_state_AppLogic_State_LoadingSaveFile : OnEnter → StartLoadingSaveFile
ankitaiso_app_state_AppLogic_State_MainMenu : OnEnter → SetupGameScene, ShowMainMenu
ankitaiso_app_state_AppLogic_State_SplashScreen : OnEnter → ShowSplashScreen
ankitaiso_app_state_AppLogic_State_SplashScreen : OnSplashScreenSkipped() → HideSplashScreen

[*] --> ankitaiso_app_state_AppLogic_State_SplashScreen
@enduml