@startuml GameTypingLogic
state "GameTypingLogic State" as ankitaiso_game_typing_state_GameTypingLogic_State {
  state "EnemySelected" as ankitaiso_game_typing_state_GameTypingLogic_State_EnemySelected
  state "NothingSelected" as ankitaiso_game_typing_state_GameTypingLogic_State_NothingSelected
}

ankitaiso_game_typing_state_GameTypingLogic_State_EnemySelected --> ankitaiso_game_typing_state_GameTypingLogic_State_EnemySelected : Initialize
ankitaiso_game_typing_state_GameTypingLogic_State_NothingSelected --> ankitaiso_game_typing_state_GameTypingLogic_State_EnemySelected : OnKeyDown

ankitaiso_game_typing_state_GameTypingLogic_State : OnIsMouseCaptured() → CaptureMouse
ankitaiso_game_typing_state_GameTypingLogic_State : OnIsPaused() → SetPauseMode
ankitaiso_game_typing_state_GameTypingLogic_State_EnemySelected : OnEnter → ShowLostScreen
ankitaiso_game_typing_state_GameTypingLogic_State_NothingSelected : OnEnter → ShowLostScreen

[*] --> ankitaiso_game_typing_state_GameTypingLogic_State_NothingSelected
@enduml