namespace kyoukaitansa.utils;

using Godot;

/// <summary>
/// Layer names generated by the third-party GodotSharp generators.
/// Allows us to access our layer constants in a type-safe way.
/// </summary>
[LayerNames]
public partial class GameLayers;
