@startuml InGameAudioLogic
state "InGameAudioLogic State" as ankitaiso_in_game_audio_state_InGameAudioLogic_State
ankitaiso_in_game_audio_state_InGameAudioLogic_State : OnCoinCollectionStarted() → PlayCoinCollected
ankitaiso_in_game_audio_state_InGameAudioLogic_State : OnGameEnded() → PlayPlayerDied, StopGameMusic
ankitaiso_in_game_audio_state_InGameAudioLogic_State : OnGameEntered() → PlayGameMusic
ankitaiso_in_game_audio_state_InGameAudioLogic_State : OnJumped() → PlayJump
ankitaiso_in_game_audio_state_InGameAudioLogic_State : OnJumpshroomUsed() → PlayBounce
ankitaiso_in_game_audio_state_InGameAudioLogic_State : OnMainMenuEntered() → PlayMainMenuMusic

[*] --> ankitaiso_in_game_audio_state_InGameAudioLogic_State
@enduml