@startuml PlayerCameraLogic
state "PlayerCameraLogic State" as ankitaiso_player_camera_state_PlayerCameraLogic_State {
  state "InputDisabled" as ankitaiso_player_camera_state_PlayerCameraLogic_State_InputDisabled
  state "InputEnabled" as ankitaiso_player_camera_state_PlayerCameraLogic_State_InputEnabled
}

ankitaiso_player_camera_state_PlayerCameraLogic_State --> ankitaiso_player_camera_state_PlayerCameraLogic_State : PhysicsTicked
ankitaiso_player_camera_state_PlayerCameraLogic_State --> ankitaiso_player_camera_state_PlayerCameraLogic_State : TargetOffsetChanged
ankitaiso_player_camera_state_PlayerCameraLogic_State --> ankitaiso_player_camera_state_PlayerCameraLogic_State : TargetPositionChanged
ankitaiso_player_camera_state_PlayerCameraLogic_State_InputDisabled --> ankitaiso_player_camera_state_PlayerCameraLogic_State_InputEnabled : EnableInput
ankitaiso_player_camera_state_PlayerCameraLogic_State_InputEnabled --> ankitaiso_player_camera_state_PlayerCameraLogic_State_InputDisabled : DisableInput
ankitaiso_player_camera_state_PlayerCameraLogic_State_InputEnabled --> ankitaiso_player_camera_state_PlayerCameraLogic_State_InputEnabled : JoyPadInputOccurred
ankitaiso_player_camera_state_PlayerCameraLogic_State_InputEnabled --> ankitaiso_player_camera_state_PlayerCameraLogic_State_InputEnabled : MouseInputOccurred

ankitaiso_player_camera_state_PlayerCameraLogic_State : OnPhysicsTicked → CameraLocalPositionChanged, CameraOffsetChanged, GimbalRotationChanged, GlobalTransformChanged

[*] --> ankitaiso_player_camera_state_PlayerCameraLogic_State_InputDisabled
@enduml