@startuml PlayerCameraLogic
state "PlayerCameraLogic State" as kyoukaitansa_player_camera_state_PlayerCameraLogic_State {
  state "InputDisabled" as kyoukaitansa_player_camera_state_PlayerCameraLogic_State_InputDisabled
  state "InputEnabled" as kyoukaitansa_player_camera_state_PlayerCameraLogic_State_InputEnabled
}

kyoukaitansa_player_camera_state_PlayerCameraLogic_State --> kyoukaitansa_player_camera_state_PlayerCameraLogic_State : PhysicsTicked
kyoukaitansa_player_camera_state_PlayerCameraLogic_State --> kyoukaitansa_player_camera_state_PlayerCameraLogic_State : TargetOffsetChanged
kyoukaitansa_player_camera_state_PlayerCameraLogic_State --> kyoukaitansa_player_camera_state_PlayerCameraLogic_State : TargetPositionChanged
kyoukaitansa_player_camera_state_PlayerCameraLogic_State_InputDisabled --> kyoukaitansa_player_camera_state_PlayerCameraLogic_State_InputEnabled : EnableInput
kyoukaitansa_player_camera_state_PlayerCameraLogic_State_InputEnabled --> kyoukaitansa_player_camera_state_PlayerCameraLogic_State_InputDisabled : DisableInput
kyoukaitansa_player_camera_state_PlayerCameraLogic_State_InputEnabled --> kyoukaitansa_player_camera_state_PlayerCameraLogic_State_InputEnabled : JoyPadInputOccurred
kyoukaitansa_player_camera_state_PlayerCameraLogic_State_InputEnabled --> kyoukaitansa_player_camera_state_PlayerCameraLogic_State_InputEnabled : MouseInputOccurred

kyoukaitansa_player_camera_state_PlayerCameraLogic_State : OnPhysicsTicked → CameraLocalPositionChanged, CameraOffsetChanged, GimbalRotationChanged, GlobalTransformChanged

[*] --> kyoukaitansa_player_camera_state_PlayerCameraLogic_State_InputDisabled
@enduml