@startuml PlayerLogic
state "PlayerLogic State" as ankitaiso_player_state_PlayerLogic_State {
  state "Alive" as ankitaiso_player_state_PlayerLogic_State_Alive {
    state "Airborne" as ankitaiso_player_state_PlayerLogic_State_Airborne {
      state "Falling" as ankitaiso_player_state_PlayerLogic_State_Falling
      state "Jumping" as ankitaiso_player_state_PlayerLogic_State_Jumping
      state "Liftoff" as ankitaiso_player_state_PlayerLogic_State_Liftoff
    }
    state "Grounded" as ankitaiso_player_state_PlayerLogic_State_Grounded {
      state "Idle" as ankitaiso_player_state_PlayerLogic_State_Idle
      state "Moving" as ankitaiso_player_state_PlayerLogic_State_Moving
    }
  }
  state "Dead" as ankitaiso_player_state_PlayerLogic_State_Dead
  state "Disabled" as ankitaiso_player_state_PlayerLogic_State_Disabled
}

ankitaiso_player_state_PlayerLogic_State_Airborne --> ankitaiso_player_state_PlayerLogic_State_Falling : StartedFalling
ankitaiso_player_state_PlayerLogic_State_Airborne --> ankitaiso_player_state_PlayerLogic_State_Idle : HitFloor
ankitaiso_player_state_PlayerLogic_State_Airborne --> ankitaiso_player_state_PlayerLogic_State_Moving : HitFloor
ankitaiso_player_state_PlayerLogic_State_Alive --> ankitaiso_player_state_PlayerLogic_State_Alive : Moved
ankitaiso_player_state_PlayerLogic_State_Alive --> ankitaiso_player_state_PlayerLogic_State_Alive : PhysicsTick
ankitaiso_player_state_PlayerLogic_State_Alive --> ankitaiso_player_state_PlayerLogic_State_Alive : Pushed
ankitaiso_player_state_PlayerLogic_State_Alive --> ankitaiso_player_state_PlayerLogic_State_Dead : Killed
ankitaiso_player_state_PlayerLogic_State_Disabled --> ankitaiso_player_state_PlayerLogic_State_Idle : Enable
ankitaiso_player_state_PlayerLogic_State_Grounded --> ankitaiso_player_state_PlayerLogic_State_Falling : LeftFloor
ankitaiso_player_state_PlayerLogic_State_Grounded --> ankitaiso_player_state_PlayerLogic_State_Jumping : Jump
ankitaiso_player_state_PlayerLogic_State_Grounded --> ankitaiso_player_state_PlayerLogic_State_Liftoff : LeftFloor
ankitaiso_player_state_PlayerLogic_State_Idle --> ankitaiso_player_state_PlayerLogic_State_Moving : StartedMovingHorizontally
ankitaiso_player_state_PlayerLogic_State_Jumping --> ankitaiso_player_state_PlayerLogic_State_Jumping : Jump
ankitaiso_player_state_PlayerLogic_State_Moving --> ankitaiso_player_state_PlayerLogic_State_Idle : StoppedMovingHorizontally

ankitaiso_player_state_PlayerLogic_State_Alive : OnPhysicsTick → MovementComputed
ankitaiso_player_state_PlayerLogic_State_Alive : OnPushed → VelocityChanged
ankitaiso_player_state_PlayerLogic_State_Disabled : OnEnter → Idle
ankitaiso_player_state_PlayerLogic_State_Falling : OnEnter → Fall
ankitaiso_player_state_PlayerLogic_State_Grounded : OnJump → VelocityChanged
ankitaiso_player_state_PlayerLogic_State_Idle : OnEnter → Idle
ankitaiso_player_state_PlayerLogic_State_Jumping : OnEnter → Jump
ankitaiso_player_state_PlayerLogic_State_Jumping : OnJump → VelocityChanged
ankitaiso_player_state_PlayerLogic_State_Liftoff : OnEnter → Jump
ankitaiso_player_state_PlayerLogic_State_Moving : OnEnter → Move

[*] --> ankitaiso_player_state_PlayerLogic_State_Disabled
@enduml