name: 🧾 Docs
on:
  push:
    paths:
      - docs/**
    branches:
      - main

jobs:
  build:
    name: 🧾 Docs
    permissions:
      contents: write
    # Only run the workflow if it's not a PR or if it's a PR from a fork.
    # This prevents duplicate workflows from running on PR's that originate
    # from the repository itself.
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_NOLOGO: true
      GODOT_SILENCE_ROOT_WARNING: true
    runs-on: ubuntu-latest
    defaults:
      run:
        # Use bash shells on all platforms.
        shell: bash
    steps:
      - name: 🧾 Checkout
        uses: actions/checkout@v4
        with:
          # If using git-lfs (large file storage), this ensures that your files
          # are checked out properly.
          lfs: false
          # Make sure any git submodules are checked out as well.
          submodules: 'recursive'

      - name: 🔬 Setup docs
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: 🧾 Generate docs
        run: ./scripts/generate-docs.ps1
        shell: pwsh

      - name: 🧾 Build docs
        run: |
          pip install mkdocs mkdocs-awesome-pages-plugin mkdocs-mermaid2-plugin mkdocs_puml_file mkdocs_puml plantuml
          mkdir public && mkdocs build -d public/docs

      - name: 🦺 Deploy docs
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
